# Weekly dependency update

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "./covid-vue-app/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "main"
    labels:
      - "npm dependencies" 
