version: "3.9"
services:
  web:
    build:
      dockerfile: Dockerfiledev
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json

