name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Covid-Application
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies with Yarn
      run: yarn
    - name: Lint with eslint
      run: yarn lint
    - name: Build with Webpack
      run: yarn build 
    - name: Run tests
      run: yarn test
