name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./covid-vue-app
    steps:
      - uses: actions/checkout@v2
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
      - name: Determine tag
        if: env.TAG == ''
        run: |
          echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
      - name: Create Image
        run: podman build . --file Dockerfile
          image: ${{ env.APP_NAME }}
          tag: ${{ env.TAG }}
          # If you don't have a dockerfile, see:
          # https://github.com/redhat-actions/buildah-build#building-from-scratch
          # Otherwise, point this to your Dockerfile relative to the repository root.
          dockerfiles: |
            ./covid-vue-app/Dockerfile
      # https://github.com/redhat-actions/push-to-registry#readme
      - name: Push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.APP_NAME }}
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
