name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./covid-vue-app
    steps:
      - uses: actions/checkout@v2
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Create Image
        run: podman build . --file Dockerfile --tag covid-vue:$(date +%s)
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: dabreadman/Node-Podman-OpenShift-CI-CD
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
