name: CI/CD

env:
  # ⬇️ EDIT with your registry and registry path.
  REGISTRY: hub.docker.com/u/${{ secrets.DOCKERHUB_USERNAME }}/
  # ⬇️ EDIT with your registry username.
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  # ⬇️ EDIT to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  # OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  # APP_PORT: 8080
  # OPENSHIFT_NAMESPACE: ""
  APP_NAME: ""
  TAG: ""

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./covid-vue-app
    steps:
      - uses: actions/checkout@v2
      - name: Print env
        run: |
          echo $USERNAME
          printenv
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
      - name: Determine tag
        if: env.TAG == ''
        run: |
          echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
      - name: Create Image
        run: podman build . --file Dockerfile --tag ${{ env.APP_NAME }}:${{ env.TAG }}
      # https://github.com/redhat-actions/push-to-registry#readme
      - name: Push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.APP_NAME }}
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
