name: Rollback

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Application name for image"
        required: true
      tag:
        description: "Image version tag"
        required: true
      namespace:
        description: "Deployment namespace"
        required: true

env:
  # Using Quay.io
  REGISTRY: quay.io
  REGISTRY_USERNAME: dabreadman

  # OpenShift Token
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_PROD }}
  APP_PORT: 8080

  APP_NAME: ${{ github.event.inputs.app_name }}
  TAG: ${{ github.event.inputs.tag }}
  
jobs:
  rollback:
    name: Rollback OpenShift to specific version
    runs-on: ubuntu-latest

    steps:
      - name: Download image
        run: podman pull ${{ env.REGISTRY }}/${{ env.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Create and expose app
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          port: ${{ env.APP_PORT }}
